# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
#title: Your awesome title
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
baseurl:
permalink: /:title/
safe: false

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-assets

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-assets

assets:
  compress:
    css: true
    js: true
  cache: false
  # cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - images
    - javascripts
    - stylesheets
    - fonts
  features:
    liquid: true
    automatic_img_size: true
    automatic_img_alt : true

exclude: ['Gruntfile.js', 'package.json', 'Procfile', 'Rakefile', 'README', 'Gemfile', 'Gemfile.lock', 'config.rb', 'vendor', 'node_modules', 'stylesheets/sass', 'images/src']
